name: Docker Image Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: git pull

      
    - name: Build the Docker image
      run: |
        ls
        docker build -t ${{ vars.REGISTRY }}/${{ vars.SPACE_NAME }}/anki-card:v0.0.1 .

    - name: Login Registry
      run: |
       echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -username=${{ secrets.DOCKER_ACCOUNT }} --password-stdin ${{ vars.REGISTRY }} 
       docker push ${{ vars.REGISTRY }}/${{ vars.SPACE_NAME }}/anki-card:v0.0.1
        
