name: Docker Image Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: git pull

      
    - name: Build the Docker image
      run: |
        ls
        docker build -t ${{ vars.SPACE_HUB_NAME }}/anki-card:v0.0.1 .

    - uses: docker/login-action@v3.2.0
      name: Docker Login
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: ${{ vars.REGISTRY }}
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_HUB_ACCOUNT }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_HUB_PWD }}
          
    - name: Push the image
      run: | 
       docker push ${{ vars.SPACE_HUB_NAME }}/anki-card:v0.0.1
        
